### ISSUE TITLE
Is there a way to configure environment variables?

### ISSUE THREAD

**Issue by Omermiz** [terraform-alicloud-modules/terraform-alicloud-fc#4]
Is there a way to set FC environment variables via TF?

https://www.alibabacloud.com/help/doc-detail/69777.html

**Comment by xiaozhu36** [comment]
HI @Omermiz I am sorry for late reply. The provider 1.36.0 has supported this feature: https://www.terraform.io/docs/providers/alicloud/r/fc_function.html#environment_variables. Please check it. 
Please let me know if you have other problems.

**Comment by xiaozhu36** [comment]
Closed by no reply.
